apiVersion: apps/v1
kind: Deployment
metadata:
  name: careerrag-app
  namespace: careerrag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: careerrag
  template:
    metadata:
      labels:
        app: careerrag
    spec:
      containers:
        - name: careerrag
          image: lakshitgupta07/careerrag:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          envFrom:
            - configMapRef:
                name: careerrag-config
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "3Gi"
              cpu: "1000m"
