apiVersion: v1
kind: Service
metadata:
  name: careerrag-service
  namespace: careerrag
  labels:
    app: careerrag
spec:
  type: NodePort
  selector:
    app: careerrag
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30851
      protocol: TCP
